- src/error_logger_lager_h.erl
- src/lager_common_test_backend.erl
in common_test, starting and stopping applications can make your logs
very noisy.  the patch allows these messages to be suppressed on the
happy path, and raises the high water mark during ct tests so that
messages aren't dropped.
> add application stop/start suppression for ct logs

- README.md
The example in "Internal log rotation" includes the tuple
{name, "error.log"}
This apparently should be
{file, "error.log"}
as seen in other config examples in README.md.
> Fix specification of backend config in log rotation example

- README.md
The readme did not mention how to set color when using custom formatting. This "fixes" that.
> Mention the color atom for the formatter config

- README.md
- src/lager_crash_log.erl
- src/lager_file_backend.erl
- src/lager_util.erl
When using multiple log files, usually all filenames have common directory.
When application has several environments (e.g. development and production) the log directory may differ.
When adding a new log file, the developer has to be careful to edit log path according to the environment.
Moving log directory to the separate environment variable allows to apply logging changes by using just ```diff``` and ```patch``` utilities. Also application config becomes shorter.
> Add optional log_root environment variable

- README.md
was not documented, very useful in production scenarios where default debug level is critical
> add per-module per-function trace example

- rebar.config
- src/error_logger_lager_h.erl
- src/lager_backend_throttle.erl
- src/lager_file_backend.erl
- test/crash.erl
- test/lager_test_backend.erl
- test/pr_nested_record_test.erl
Includes several test failure fixes, a Unicode bug fix and updates goldrush to release 0.1.7.
The 2.x branch is a maintenance branch intended for lager users who do not wish to use the lager 3.0 code or its API semantics.
> Update lager 2.x for OTP 17

- README.md
- include/lager.hrl
- src/lager.erl
- src/lager_transform.erl
- test/lager_test_backend.erl
This branch adds a new `_unsafe` path for log messages with a reasonable bounded size when its not necessary for lager to ensure that log messages don't kill an application because they're so huge.
> Add an unsafe_formatting code path

- include/lager.hrl
- src/error_logger_lager_h.erl
- src/lager.erl
- src/lager_file_backend.erl
- src/lager_util.erl
Services using lager have to face high velocity of incoming messages, which would overflow the file backend. The situation is desperate when something abnormal events happen, and especially we're using cloud hosts.
The config error_logger_hwm only effects error_logger redirected but the raw file backend,  IIRC. So I add a similar configuration high_water_mark.
To be friendly for the PR, I've split it to three parts: 
1. Refactor the error_logger_hwm control codes, make it public to all modules by moving to lager_util;
2. add high_water_mark configuration to lager_file_backend;
3. add set_loghwm method to change high water mark on the fly.
Thanks in advance for your review.
> Flow control messages to lager_file_backend by adding high water mark

- src/lager.erl
- test/compress_pr_record_test.erl
Sometimes there are a LOT of records going through logging backends
which contain notable number of empty (i.e. undefined) fields. This
humble patch solemnly introduces new function `lager:pr/3` designed to
help cope with such kind of issues, providing a one and only option `compress`
which, when turned on, effectively eliminates any empty fields in records.
> Provide means to compress printed record output

- src/lager.erl
- src/lager_file_backend.erl
This is a little bugfix for trace_file funktion.
> trace_file don't work, if env "log_root" is set.

- src/error_logger_lager_h.erl
- test/lager_test_backend.erl
Hi,
I stumbled upon errors in log file about FORMAT ERROR, it turns out that problem was that some library sometimes sends unicode data via error_logger:xxx_msg calls. 
Looking into code I saw that problem is in error_logger handler that call lager:safe_format twitce in some cases - first properly with Fmt, Args, and second time with already formatted string (in lager:log).
As no unicode characters are allowed in format string I see this errors in log.
So I removed  premature formating from error_logger backend for messages, calling just lager:log, it seems that solves the problem.
> Fix  FORMAT ERROR in error_logger backend

- src/lager_default_formatter.erl
`Width :: integer() | {left  | right | centre, integer()}`
placeholders: date, time, message, sev, metadata and new placeholder `blank::blank | {blank, string()}` ignore Width param
example :
* `["[",{undef, "", [severity], {right, 10}},"]"] ->`    if severity is error  print [&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;error]
* `["[",{undef, "", [severity], {left, 10}},"]"] ->`      if severity is error  print [error&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]
* `["[",{undef, "", [severity], {centre, 10}},"]"] ->` if severity is error  print [&nbsp;&nbsp;error&nbsp;&nbsp;&nbsp;]
* `["[",{undef, "", [severity], 10},"]"] ->`               if severity is error  print [error&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]
* `["[",{undef, "", [severity,{blank,"|"},severity], {left, 10}},"]"] ->`   if severity is error  print …
> Add option to format output with Width param in lager_default_formatter

- src/lager_stdlib.erl
- test/trunc_io_eqc.erl
255 is a valid ISO-8859-1 character. This was fixed on 2.x by #292. Forward port the fix into 3.x.
> Forward port #292 to 3.x branch

- src/lager_stdlib.erl
- test/trunc_io_eqc.erl
At least for ISO 8859-1 (aka Latin-1) [1], 255 is one of its
characters.
Behavior before this commit:
```
9> lager:log(info, self(), ["254 is ok: ", 254]).
ok
17:55:11.624 [info] 254 is ok: þÿ
10> lager:log(info, self(), ["255 is not considered as \"character\" (sadpanda)", 255]).
ok
17:55:15.080 [info] FORMAT ERROR: ["255 is not considered as \"character\" (sadpanda)",255] []
```
[1] https://en.wikipedia.org/wiki/ISO/IEC_8859-1
> Accept 255 (or 0xFF in hexadecimal) for format strings

- README.md
- include/lager.hrl
- src/error_logger_lager_h.erl
- test/lager_test_backend.erl
If `error_logger_lager_event` sink is defined, all `error_logger` messages goes to this sink, otherwise - default sink. 
This provides opportunity to separate application logs and `error_logger` logs.
> Support for separate sink for error_logger messages

- src/lager.erl
- test/lager_test_backend.erl
As identified in PR #267, the argument ordering in the internal representation of a trace tuple as returned by `validate_trace_filters` is different from the external representation, and we had the external ordering in the function head.
This prevented backends from being stopped or removed if no other traces were active for that backend.
> Fix internal tuple argument order

- rebar.config
The upstream goldrush library added support for not equal filters. All lager tests pass.
> Bump goldrush to 0.1.8 for not equal filters

- src/lager_app.erl
Previously, if you configured a trace to use an extra sink, you'd get a noproc error. Addresses issue #296 on github.
> Start traces after extra sinks are started

- rebar.config
This mirrors a bump on the master (3.x) branch #313
> Bump goldrush to 0.1.8

- src/lager_file_backend.erl
This PR supersedes #312 and includes a trivial fix for an unmatched function return that makes dialyzer cranky.
> Close file right after rotation

- README.md
- src/error_logger_lager_h.erl
- src/lager.app.src
Application variable `error_logger_format_raw` when set to `true` prevents error_logger messages from reformatting.
> Option to not reformat error_logger messages

- src/lager.erl
- src/lager_file_backend.erl
- test/lager_rotate.erl
Can be used with `logrotate` scripts to have more control over log rotation, while still using lager log rotation features.
> API to explicitly call log rotation

- src/error_logger_lager_h.erl
- src/lager_app.erl
- src/lager_stdlib.erl
- src/lager_sup.erl
Thanks to @zzantozz and @tonyrog for prodding us on this. We already had a compatibility function for R15 in `lager_app`; this exposes it and uses it in `error_logger_lager_h`.
Addresses #329 (RIAK-2436) and supersedes #325 (RIAK-1644).
> Leverage existing lager_app:get_env wrapper for error_logger_lager_h

- src/error_logger_lager_h.erl
The `stdlib` module `supervisor` reports the child name as `id` now vs `name` previously
> Address #332: try both id and name

- test/lager_test_backend.erl
The sync_error_logger file looks up the message level with which to tag a message from a process dictionary entry named `warning_map'. When it is unset, it uses a default mapping which is fine for OTP 17 and before, but in OTP 18 and 19 the value changed from this default.
Now we put the current error logger warning mapping value into the process dictionary regardless of what OTP release tests are running under so that the messages do not cause failed tests if the default mismatches the OTP release default.
Addresses #275
> Put the warning map value into process dictionary (Fix OTP 18 test failures)

- src/lager_app.erl
Address #286 (RIAK-2094). This will enable applications to
dynamically configure log sinks, provided they
have already instrumented the code via parse
transformation to use those sinks.
> Export configure_sink/2 for runtime sink config

- src/lager.erl
- test/lager_rotate.erl
- test/zzzz_gh280_crash.erl
* filtermap - if we're going to have R15 as a Travis tested platform, this is required to ensure the implementation of the rotate sink feature does not break. (includes a dialyzer fixup)
* replace timer:sleep with wait_until
* increase timeout on gh280 test - 30 second for eunit, 10 seconds to receive the message
> Flappy test clean up for TravisCI

- README.md
- src/lager_app.erl
- src/lager_file_backend.erl
- test/lager_test_backend.erl
Thanks to @nmichel - I wanted to handle traces defined in the configuration file consistently without a new keyword. So this is intended to supersede #315 but is *slightly* less functional because it doesn't allow the `Options` but on the other hand, it doesn't introduce a new configuration keyword either.
There is apparently a delay in flushing the log messages to files and so we have an evil timer:sleep/1 call in this test. I don't know of a good way to force the lager file backend to flush a file handle to disk on demand though. (Maybe it should be part of the API? Not sure right now.)
> Ensure traces pointed to files work in config file

- src/lager.erl
Addresses #291 (RIAK-2156). External consumers who use 'none' as a level in their log messages will fail dialyzer.
> Include 'none' in the log_level type

- README.md
- rebar.config
- src/lager_app.erl
- src/lager_file_backend.erl
- src/lager_handler_watcher.erl
- src/lager_manager_killer.erl
- test/lager_manager_killer_test.erl
- test/lager_slow_backend.erl
- test/lager_test_backend.erl
Heavily based on work by @jinnipark and @blt, this pull request implements an optional "killer" manager which brutally kills itself as a means of load shedding if a high water mark is reached in the gen_event manager's process mailbox.
Incorporates and supersedes #328. Addresses #324
> Incorporate an optional 'sink killer' for load shedding purposes

- src/lager_transform.erl
Otherwise `lager_transform` fails after https://github.com/erlang/otp/commit/de9012628a6b0e97d2f1325bf2f72817f69f84ee
The error message is:
test/pr_nested_record_test.erl: error in parse transform 'lager_transform': {function_clause,
[{lager_transform,
'-walk_ast/2-fun-0-',
[{typed_record_field,
{record_field,5,
{atom,5,field1}},
{type,5,term,[]}}],
[{file,
"src/lager_transform.erl"},
{line,62}]},
> Support typed records newly exposed in OTP 19

- src/lager_app.erl
- src/lager_handler_watcher.erl
* Undo unnecessary whitespace
* Make lager_handler_watcher test more resilient by scanning for
messages of interest rather than assuming we know exactly what
messages will arrive at the test backend
* `export_all` to allow R15 to run the `lager_app_tests` tests
> Cleanup for test, whitespace

- src/lager_sup.erl
Applications that explicitly configure lager's `crash_log` with the
value `undefined` will get a really terrible crash message for all
versions since 81222ca4869402b4b790bce3f2df40f9b2d213a0
Diff here: https://github.com/basho/lager/commit/81222ca4869402b4b790bce3f2df40f9b2d213a0#diff-25e915f0df09d04052d2a6e85b8824f2
That message looks like this:
```
** Generic server lager_crash_log terminating
** Last message in was rotate
** When Server state == {state,undefined,
{file_descriptor,prim_file,{#Port<0.1340>,15}},
281571,65536,10485760,
[{hour,0}],
5,false}
** Reason for termination ==
** {badarg,[{erlang,'++',[undefined,".3"],[]},
{lager_util,rotate_logfile,2,
[{file,"_build/default/lib/lager/src/lager_util.erl"},
{line,220}]},
{lager_crash_log,handle_info,2, …
```
> Fixed legacy support for {crash_log, undefined}

- README.md
- src/lager.app.src
Hi:
The `crash_log` application var should be `false`.
Long long ago, it's `undefined`. But, if I set it `undefined` now, the whole node will be crash.
```
16:53:51.007 [error] gen_server lager_crash_log terminated with reason: bad argument in call to erlang:'++'(undefined, ".3") in lager_util:rotate_logfile/2 line 220
16:53:51.007 [error] CRASH REPORT Process lager_crash_log with 0 neighbours exited with reason: bad argument in call to erlang:'++'(undefined, ".3") in lager_util:rotate_logfile/2 line 220
16:53:51.007 [error] Supervisor lager_sup had child lager_crash_log started with lager_crash_log:start_link(undefined, 65536, 10485760, [{hour,0}], 5) at <0.1321.0> exit with reason bad argument in call to erlang:'++'(undefined, ".3") in lager_util:rotate_logfile/2 line 220 in context …
```
> mark for no crash log

- src/lager_app.erl
The strict configuration work in 31cf6c0 prevents some
backwards-compatible code in lager_file_backend from working as the
configuration is rejected before it gets to the backend. This fix adds
an additional guard on `check_handler_config/2` to support the `tuple`
configuration structure supported by `lager_file_backend`.
> Restore backwards-compatible `lager_file_backend` configurations.

- src/lager_crash_log.erl
- src/lager_file_backend.erl
Add `| undefined` to records that get initialized with not all their set to the proper type (hence get the value undefined). These allow lager to exist as a dependency in a project and be filtered through that project's dialyzer run without warnings.
> Fix dialyzer warnings

- .travis.yml
TravisCI now supports testing on 18.3 and 19.0. This PR updates the `.travis.yml` file to run tests against those OTP releases.
Switching to 18.3 instead of 18.2.1 makes sense as that's the release most will be targeting for 18.x
> Update TravisCI for OTP 18.3 and 19.0

- README.md
It wasn't clear whether "it" referred to async_threshold or async_threshold_window.
> Make "it" unambiguous

- src/lager_default_formatter.erl
Introduces the option to have severity logged in uppercase letters, as is usual for other programs logging to syslog, for example.
> Add an uppercase severity formatter

- src/lager_transform.erl
- test/lager_test_backend.erl
This allows users to log metadata (tuple list) without a format string in lager. For
example `lager:info([{foo, bar}])` instead of `lager:info([{foo,bar}], "")`.
> Allow Metadata-only logging

- src/lager_crash_log.erl
- src/lager_file_backend.erl
- src/lager_util.erl
- test/lager_rotate.erl
* Fix `lager_util:rotate_file_fail_test/0` to use `chmod`, as intended, instead of `chown`.
* Adds functions to create and delete separate directories for test files.
* Change all tests that use temporary files to use the above.
Turn off whitespace diffs to review, as much code has been shifted left to allow sane wrapping within around 100 columns.
> Bugfix and separate test files directory.

- src/lager_crash_log.erl
- src/lager_file_backend.erl
- src/lager_util.erl
- test/lager_rotate.erl
- test/lager_test_backend.erl
This PR extends the changes in https://github.com/erlang-lager/lager/pull/384 - it ***may*** be mergeable separately, but has not been tested independently.
Initially, problems with `async_threshold_test_` were thought to be related to newer versions of OTP _and/or_ newer multicore CPUs handling messages more efficiently, thereby preventing automatic transition to synchronous `lager` message handling.
After many experimental changes, it appears that the root problem was pollution of the test environment by previous external tests that don't clean up after themselves properly, so this test now rigorously scrubs its environment before running.  The changes already in place are deemed worthwhile and have been kept.
Timeout issues with `trace_files_test_`, where we don't know how long it will …
> Fix async_threshold_test_ and trace_files_test_ flappiness.

- test/lager_test_backend.erl
While the test works fine on a local system, running this test in Travis requires a higher timeout threshold. (There have been consistent test failures on OTP 19 for this test taking too long.)
> Travis needs a higher timeout for the async test

- src/error_logger_lager_h.erl
Previously, error_logger messages only had the pid of the crashed
process, not any of the traditional lager metadata like
module, function, line, etc.
It turns out, however, that we already have most if not all of that
information as metadata already in the stack trace. Thus, we can capture
it and re-inject the error logger log message as a lager message with
metadata.
Additionally, when a process crashes, we get the process dictionary
passed to us, which we can scan for the '_lager_metadata' entry, and
attach the dead process' metadata to the log message as well.
> Capture error-site metadata from error_logger messages & feed them to lager

- rebar.config
- src/error_logger_lager_h.erl
- test/crash_fsm.erl
- test/crash_statem.erl
- test/lager_test_backend.erl
Based on and supersedes #377.
Includes unit tests for the crash messages and formatting for both gen_fsm and gen_statem.
> Format gen_fsm/gen_statem crashes correctly

- src/lager.erl
- src/lager_util.erl
- test/lager_trace_test.erl
Previously the following configuration didn't work properly:
{log_root, "logs"},
{handlers, [{lager_file_backend, [{file, "access.log"}, {level, none}, ...]}]},
{traces, [{{lager_file_backend, "access.log"}, [{tag, access}], info}]}
When lager:trace_file was trying to find a file among the existing handlers, it was searching for the expanded file name ("logs/access.log"), but the handlers store the file names without expansion ("access.log"), so it didn't find it.
The result was that lager:trace_file started another "access.log" backend, which of course didn't use e.g. the log rotation settings of the first handler. When the log_root was relative, then each log message appeared twice in the log file (both backends thought that they should log it, because when calculating the Destination, …
> Fix path expansion for traces when log_root is set

- README.md
- test/lager_test_backend.erl
Add documentation and tests for the UTC time feature.
Feel free to improve or propose modifications. I'm not really good with words!
Cheers
Related issue: https://github.com/erlang-lager/lager/issues/401
> Issue #401: Document and test the UTC time feature

- rebar.config
- src/error_logger_lager_h.erl
- test/lager_test_backend.erl
* Handle new gen_server crash messages that contain client pid and stacktrace
* Update platform define for OTP 20
* Handle arity change in gen_fsm handle_msg
> Fixes for OTP 20

- README.md
- src/lager_app.erl
- src/lager_console_backend.erl
Also rationalized the configuration options for the console backend and adds deprecation warnings for the older configuration styles.
TODO:
@Vagabond what would be a good way to test these changes?  We have a little pretend group leader shim in the unit tests. Can we use the same technique for `standard_error`
Addresses #168
> Enable sending console output to standard error

- include/lager.hrl
- src/error_logger_lager_h.erl
- src/lager_file_backend.erl
- src/lager_util.erl
* If the shaper is in overload and the final message comes in, but no
further messages arrive for some time, until another message came in,
the drop count would not be printed. Now we set a timer to ensure it
prints the drop count after the current second expires.
* Allow the shaper to take a filter function that allows events that
would not normally be printed anyway to not be counted against the
HWM. This means that if you're suppressing supervisor startup messages
you won't see drop events counted for messages you'd never see
printed.
> Make the high water mark shaper better

- README.md
`application` is a metadata placeholder but isn't listed in the documentation. This is pull is to add it to the README
> Added info about application place holder.

- README.md
Emphasize application variable, since I missed it. 
A little emphasis may help.
> A little emphasis on application variable crash_log

- src/lager.erl
- test/pr_stacktrace_test.erl
Setting `reverse_pretty_stacktrace` to `false` results in:
```
error:undef
lists:concat([], [])
pr_stacktrace_test:pr_stacktrace_bad_arity_test/0 line 60
```
Instead of:
```
pr_stacktrace_test:pr_stacktrace_bad_arity_test/0 line 46
lists:concat([], [])
error:undef
```
> add reverse_pretty_stacktrace env var, default true

- README.md
- include/lager.hrl
- src/error_logger_lager_h.erl
- src/lager_file_backend.erl
- src/lager_util.erl
We've been chasing weird timeout bugs in our test suites, presumably due to race conditions, but recently realized that lager was hitting the high-water mark and actually _deleting_ `app_started` events that our test suite depended on. This behavior violates the Principle of Least Surprise, to say the least.
In the interest of backward compatibility, I've made the behavior configurable, for `error_logger` and for each sink. I have, though, chosen the b/w incompatible default of _not_ flushing events. As long as it's properly documented and configurable, which should be the default can of course be discussed.
> Dont flush notify msgs at overload

- include/lager.hrl
- test/lager_test_backend.erl
With new macros being supported in OTP it makes sense to provide a macro interface to lager as well.
There are still some forms of these functions I need to support, like `?info_unsafe`? I stopped here to check that this was an acceptable change upstream and if so that the api was what you'd want.
> support logging with macros per level

- README.md
- src/lager.app.src
- src/lager_crash_log.erl
- src/lager_file_backend.erl
- src/lager_rotator_behaviour.erl
- src/lager_rotator_default.erl
- src/lager_sup.erl
- src/lager_util.erl
I am seeking to use `lager` as the logging back-end for LeoFS, so would like to open up the possibility of custom log rotator.
This should not change the current behaviour, only when user opt-in with custom log rotator
> Add custom log rotator option and hourly log rotation

- src/error_logger_lager_h.erl
- src/lager.erl
- src/lager_app.erl
- src/lager_stdlib.erl
- src/lager_sup.erl
- test/lager_app_tests.erl
- test/lager_test_backend.erl
Fixes #399 
Perhaps the comments for https://github.com/erlang-lager/lager/blob/master/src/error_logger_lager_h.erl#L403 and https://github.com/erlang-lager/lager/blob/master/src/error_logger_lager_h.erl#L477 need updating but aside from that I think I've got it all.
geas output
```
~/src/lager (remove-r15) $ rebar3 geas
===> Verifying dependencies...
===> Compiling lager
R15                   20.2       Geas database
---Min--------Arch-------Max----------------------------------------------------
goldrush
17.0                             lager
goldrush
17.0                             lager
17.0                             lager
--------------------------------------------------------------------------------
17.0                  20.2       Global project …
```
> Remove code which supports R15

- src/error_logger_lager_h.erl
- src/lager_util.erl
Turns out that previous shaper PR I merged was not quite baked, sorry.
* `should_flush` was case_clausing
* the default for error_logger queue flushing was not set to true
* the dropped message count was being incorrectly incremented
If this looks good, we should cut a patch release ASAP @mrallen1
> Make a few corrections to the recent mailbox flushing changes

- include/lager.hrl
This is to suppress dialyzer's `unmatched_return` warning
> Ignore return value of lager:dispatch_log in lager.hrl

- src/lager_app.erl
In some projects using lager, without configuration, this error turns out:
```
WARNING: This is a deprecated console configuration. Please use "[{level,info}]" instead.
```
I think this patch will be work.
> use "[{level,info}]" instead

- README.md
According to the official changelog for elixir 1.5 parse_transform is
deprecated since this version. See
https://github.com/elixir-lang/elixir/blob/v1.5/CHANGELOG.md#4-deprecations
> Update Elixir section with information about parse_transform

- src/lager_default_formatter.erl
Closes #309. This will enable the use of `node` in log formatting. It uses the value of the `node()` function via `atom_to_list/1` to output a value.
There is a simple test case.
> Add `node` as a formatting option

- .travis.yml
- rebar.config
- src/lager_app.erl
To support OTP 21 we manually start error_logger if it is not present
(and lager is configured to install an error_logger handler) and we add
error_logger as a logger handler.
Longer term we should switch to installing our own logger handler, but
that is a larger task as we'd have to redo all the event parsing, if
that is even possible.
Related to #455
> OTP 21 support

- rebar.config
Rebar's internal mechanism for matching the `platform_define` config option could match against the full system architecture in addition to the OTP release version.
```
1> rebar_utils:get_arch()
"20.3.8-x86_64-apple-darwin18.0.0-64"
```
On the latest macOS kernel (architecture string above), the `platform_define` case in rebar.config:
```
{platform_define, "(18)", 'FUNCTION_NAME', unavailable},
```
would match, causing the FUNCTION_NAME macro to be redefined and prevent compilation with the following error:
```
===> Compiling lager
/Users/howard/Documents/erlang/nexthaul/_build/default/lib/lager/src/lager_util.erl: redefining predefined macro 'FUNCTION_NAME'
===> Compiling _build/default/lib/lager/src/lager_util.erl failed
_build/default/lib/lager/src/lager_util.erl:none: redefining …
```
> Fixed platform_define pattern matching

- README.md
It fixes this wring markup formatting:
The result:
> Fix markup - inline code

- README.md
- src/lager.erl
- src/lager_console_backend.erl
To support tracing to a console that is not the erlang node's *direct*
console introduce 2 additional options to the console backend:
`group_leader` and `id`. Group leader allows to use io:put_chars to send
the console output to a remote pid (eg. the group leader on a node
created by nodetool) and the ID allows multiple console backends to
exist simultaneously (for example {lager_console_backend, NodeName}).
Additionally, to support ephemeral console backends with associated
traces, if the console handler explicitly removes itself from the event
handler, remove any traces for that id.
To facilitate this, a new function has been added to the lager module:
`lager:clear_trace_by_destination/1`.
> Allow the console backend to redirect output to a remote node

- src/error_logger_lager_h.erl
- test/crash_statem.erl
- test/lager_test_backend.erl
This should be a fix for #471.
No direct test is provided because, as mentioned in the issue, I believe this is undefined behaviour.
> Handle strange crash report from gen_statem

- src/lager.erl
- test/pr_composite_test.erl
The list comprehension fail on improper lists, use a recursive
call into pr/2 instead.
Fixes #477.
> replace list comprehension with recursive invokation in pr/2

- src/error_logger_lager_h.erl
- src/lager_util.erl
During further testing found one more bug in check_hwm
This fix is an addition to https://github.com/erlang-lager/lager/pull/467
I have to add this one more fix. The logic appeared to be more complicated and I missed one more bug in check_hwm. Hope now it should be ok. The fix does not look beautiful, sorry.
> Fix check_hwm

- README.md
- src/lager.erl
By an unhappy accident, OTP21 added functionality for 'named' trace
functions. This has a pattern match that matches the old trace function
(a 2 tuple where the second element is itself a 2 tuple):
https://github.com/erlang/otp/pull/1781
This patch changes to using a versioned record (so we can extend the
tracing later if needed) and adds 3 more options to tracing; count,
timeout and format string.
Additionally, tracing an OTP process via start_link arguments is now
documented.
> Improve debug tracing support

- .gitignore
- src/lager_trunc_io.erl
Current lager requires Erlang/OTP >= 18 so no check required.
> Remove check for erlang:is_map/1

- src/lager_file_backend.erl
- src/lager_rotator_default.erl
To reproduce -
* Install RabbitMQ 3.7.12 and Erlang 21.2 on Windows
* Start up RabbitMQ, and run `rabbitmqctl rotate_logs`
* You will see the log file rotated, but nothing ever gets logged to the new file
Windows requires that all handles to a file are closed prior to renaming the file, which is why I moved `close_file` prior to `Rotator:rotate_logfile`. What I also found is that subsequent calls to `lager_rotator_default:ensure_logfile` would always fail to open the file since, on Windows, `Inode` is always `0`.
Adding a function head that matches the `undefined` `FD` case will ensure that the file is opened, which I believe is what we want no matter the underlying OS.
> Fix rotation on Windows

- src/error_logger_lager_h.erl
- src/lager.erl
- src/lager_app.erl
- src/lager_file_backend.erl
- src/lager_handler_watcher.erl
- src/lager_rotator_default.erl
- src/lager_util.erl
This pull request has been created to solve issue #500. Please review.
Change details:
- Unnecessary case branch removed in error_logger_lager_h.erl:367 (?LOGFMT returns logged | no_log).
- Added pattern "_ =" to cases where return value of the expression is not used.
Regards,
Viktor
> Fix dialyzer errors

- src/lager.erl
- src/lager_crash_log.erl
- src/lager_file_backend.erl
Tested by setting the following environment variable on `win32` prior to starting RabbitMQ:
```
set RABBITMQ_BASE=C:\ProgramData\찦차를 타고 온 펲시맨과 쑛다리 똠방각하 (Korean)\RabbitMQ
```
> Add t to string formatting to accept unicode file and dir names

- src/lager_default_formatter.erl
- test/lager_metadata_whitelist_test.erl
Allow to create a metadata whitelist in `sys.config` so that you do not have to create a custom formatter.
```
[{lager, [
{metadata_whitelist, [request_id]}
]}]
```
It will print them (using the default formatter):
```... [error]  request_id=123 Message```
> Metadata whitelist

- src/error_logger_lager_h.erl
There's probably more, and I haven't actually tested this, but needed to get this off my laptop
> Try to handle another way gen_statem logs crashes

- src/lager_transform.erl
Due to an [upcoming change](https://github.com/erlang/otp/pull/3006) to the way location gets reported by the compiler, `lager` executes with error in Erlang/OTP `master`. This pull request fixes the only place I saw this occurrence failing, though there may be others 🤷‍♂️.
> Adapt to OTP 24's Line v. {Line,Col} location

- src/lager.app.src
- src/lager_app.erl
- src/lager_sup.erl
Since `crash.log` is assumed defined, by default (otherwise it has to be defined as `false` or `undefined` explicity - something I don't usually do), if I define `log_root` and not `crash_log`, I get `crash_log` as `"<myfolder>/log/crash.log"`.
I'd prefer to have `crash.log` directly in `<myfolder>`. The proposed solution aims for backward compatibility.
**Edit**: I guess the same could be applied to the `DEFAULT_HANDLER_CONF`, though not setting `handlers` is probably less common than not setting `crash_log`.
> Allow log_root on crash_log

- src/lager_util.erl
Currently, if `log_root` is e.g. `log` and `console.log` is not specified with a "folder", `log_root`'s value is not taken into account (give the nature of `src`).
This proposed approach does not, however, allow for e.g. `log/console.log` to be saved in `logs/log/console.log` (in case `log_root` is defined), but I believe that's not the common use; otherwise we might add a new option (always use `log_root`) that would allow for this mis-behaviour to occur.
---
Of course, to be perfectly strict, and do away with these workarounds, we'd always apply `log_root` as a prefix, independent of what is chosen as file name, since that's the semantics of `log_root`, it seems.
> Prevent "wrong" log location

- .github/workflows/ci.yml
- .travis.yml
- README.md
- rebar.config
- src/lager.erl
- src/lager_transform.erl
- test/crash_statem.erl
- test/lager_test_backend.erl
- test/pr_stacktrace_test.erl
This pull request builds on top of [my previous one](https://github.com/erlang-lager/lager/pull/537/files).
On the one hand, I prefer `erl_anno:line/1` to matching on an "opaque" structure, since this eases maintenance.
On the other hand, with a more recent version of OTP (from `master`), I got new warnings (introduced by new behaviour from https://github.com/erlang/otp/pull/2995), now fixed.
**Note**: this doesn't fundamentally change the way we handle the location, but it meant I was assuming that the format for that might not change, which might not be true (since OTP 24 isn't out yet).
> Further adapt to OTP 24 + adopt GHA

- .github/workflows/ci.yml
- appveyor.yml
- src/lager_util.erl
- test/pr_stacktrace_test.erl
This is a proposed fix that hopefully closes #542.~~, to get early feedback.~~
Apart from the obvious variable re-naming (it's not a rel. path anymore), I went with the approach described [here](https://github.com/erlang-lager/lager/issues/542#issuecomment-786599680).
I also prevent the `application:get_env` from being called when it's not required. Mind you, this is untested still.
---
**Edit**: what's done?
> Log to log_root+..._log except if ..._log is absolute

- src/lager_transform.erl
We use a construct, as suggested by @bjorng, to modify the generated marker.
This potentially closes #546, as reported by @michaelklishin, with the implementation suggested by @bjorng in https://github.com/erlang/otp/issues/4576#issuecomment-791188167.
@Vagabond: this prevents any change to consumer code since we actually just address the issue. Lemme know if it's acceptable.
@michaelklishin, once tests are passing, if you have time, I invite you to test this version to see if the issue goes away completely, for you.
> Prevent "a term is constructed, but never used" warning

- .github/workflows/ci.yml
(moved away from `gleam-lang/setup-erlang` since it doesn't support Windows with Erlang 24)
> Add Windows + Erlang 24 to CI

- src/lager_transform.erl
See https://github.com/erlang-lager/lager/issues/558
> Separate 'line' and 'col' metadata on OTP-24

- src/lager_file_backend.erl
- src/lager_rotator_default.erl
There is a problem, when shaper expired and try drop logs, it can reopen log file, but doesn't save file handle. After this it reopen this file again, but first handle will never close, and old log file never delete from file system (until process dies)
Also try to escape edge-case bug: close reopened logfile with same name but new inode, when new file is exceed size limit.
> Save state with new logfile handle when drop logs in shaper_expired

- src/lager_app.erl
Erlang's logger:remove_handler() doesn't provide a specific error for the handler not existing, but the source indicates that it will always be:
{badmatch, {error, {not_found, default}}}
So suppress the error message in that specific case.
> Suppress error when default logger handler already removed

- src/lager_transform.erl
Declare to the compiler that column mode is not supported
Therefore, there is no need to process variable 'Line' is {Line, Culumn} tuple,  Its value is definitely an integer
> OTP24 error_location support in lager_transform.erl
