src/lager_app.erl
Tested on my end under R15B01, the oldest Erlang I have handy. Very minor tweak.
=> Fix R15 compatibility

src/lager_default_formatter.erl
Metadata can be printed with standard or custom internal seperators ad field
seperators. The defaults are "=" and " ":
"key1=value1 key2=value2"
=> Add option to print all metadata in the default formatter

src/lager_app.erl, src/lager_default_formatter.erl, src/lager_file_backend.erl, src/lager_transform.erl
Fix some typos in source files
=> Fix several typos in srcs

README.md, src/error_logger_lager_h.erl, src/lager.erl, test/pr_stacktrace_test.erl
During development is useful to have means for printing stacktrace in human readable form.
=> Function for printing stacktrace in human readable form

src/lager.erl, test/lager_test_backend.erl
See PR #306 for details. This is a back port. Fixes #267
=> Backport fix from #306 into 2.x branch

src/lager_util.erl
If expand_path/1 already contains LogRoot in its RelPath, do not add it again. Addresses the problem in #304 (RIAK-1367) (RIAK-2326)
=> Do not add logroot in expand_path sometimes

test/lager_test_backend.erl
=> Backport OTP 18 test fixes from 3.x branch

src/error_logger_lager_h.erl
=> Backport field name change from 3.x branch

README.md
=> Fix sink name typo in docs

rebar.config, src/lager_app.erl, test/lager_app_tests.erl
Fix for https://github.com/basho/lager/issues/354
=> Fix get_env bug

README.md, src/lager.app.src
Update README.md and lager.app.src for 3.2.2 release.
=> Roll 3.2.2

src/lager_util.erl
Closes #393. Breakfix for R15 introduced in #384.
=> Crude but effective fix for #393

README.md
Documentation for Elixir usage of Lager. #348 
I aimed to provide the useful context that would allow elixir developers to make a choice between directly usage or the more idiomatic Lager as a Logger Backend approach. 
I felt it would be overkill to add elixir example for every Erlang snippet in the README.
=> Added elixir section to README

README.md
This is a little problem, it will be better to fix it.
=> Fix the bug with the wrong format.

src/lager_format.erl, src/lager_trunc_io.erl
=> Support unicode format string

src/error_logger_lager_h.erl, src/lager_file_backend.erl
=> Don't log when we dropped 0 messages

src/lager_file_backend.erl
Fix incorrect option name validation.
=> Bugfix. flush_threshold not working.

README.md, src/lager.erl
I did this a few weeks ago and it's been quite useful.
=> Add a wrapper to allow lager to install a sys trace function

src/lager_util.erl
it was not clear to me and i was using atom as `SeverityThreshold`
=> is_loggble - support for severity as atom

src/error_logger_lager_h.erl
Was 16, is now 15 after we merged #475
=> Check for the right number of dropped messages

src/error_logger_lager_h.erl, test/lager_test_backend.erl
https://github.com/ninenines/cowboy/blob/c998673eb009da2ea4dc0e6ef0332534cf679cc4/src/cowboy_stream_h.erl#L153-L157
closes #482 
closes #425
=> Handle errors generated by cowboy which were treated as ranch errors

src/lager_app.erl
=> Maybe remove OTP 21 logger default handler

src/error_logger_lager_h.erl, src/lager_handler_watcher.erl, test/lager_test_backend.erl
Includes and supersedes #497 
Fixes #496
=> Fix for incorrectly counting dropped messages

.travis.yml, rebar.config, src/error_logger_lager_h.erl
=> Prepare for Erlang/OTP 22

README.md
I used [shields.io](https://shields.io/) to make a Hex badge for Lager.
It should look something like this:
Cheers
=> Add Hex badge

src/lager_util.erl
Fix #534 
- Change lager_util:expand_path function will return abspath not relative
- Fix testcase of expand_path
- Delete function filename:absname call in lager_util:find_file，because of lager_util:expand_path will return abspath
=> Ensure relative log file not change when current path changed

README.md, src/lager_util.erl, test/lager_trace_test.erl
Replaces #516 
Rebased on latest upstream master. Added test case and documentation.
=> Allow trace filter to silence log output (updated)
